-- Default (Unknown) row for each SB_DWH DIM table
-- DIMENSION_KEY / *_SK = -1, all other columns = NULL

INSERT INTO SB_DWH.DIM_CLOS_APPLICATION
  (DIMENSION_KEY, APPLICATION_SK, WI_NAME, LOANCASEID, STREAM, CREDIT_PROFILE, CREATE_EMPLOYEE_CODE, CREATE_EMPLOYEE_NAME, CREATION_DATE, APP_GRP, HAVE_ANY_DEVIATION, ZONE, LOAN_PURPOSE, EMAIL, DISTANCE_BRANCH_CUSTOMER, PRODUCT_LINE, SUB_PRODUCT, ID_NUMBER, CHANNEL, EFF_DATE, EXP_DATE)
VALUES
  (-1, -1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO SB_DWH.DIM_CLOS_CUSTOMER
  (DIMENSION_KEY, CUSTOMER_SK, ID_NUMBER, FULL_NAME, CUST_GROUP, CUST_CATEGORY, PRECUSTGROUP, INDUSTRY_LVL1_CODE, INDUSTRY_LVL2_CODE, INDUSTRY_LVL3_CODE, EFF_DATE, EXP_DATE)
VALUES
  (-1, -1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO SB_DWH.DIM_CLOS_EXCEPTION
  (DIMENSION_KEY, EXCEPTION_SK, EXCEPTION_BK, ACTIVITYNAME, DECISION_CODE, EXCEPTION_CATEGORY, EXCEPTION_NAME, EXCEPTION_CODE, RAISE_FLAG, CLEAR_FLAG, ID_SOURCE, CODE_SOURCE, STATUS, EFF_DATE, EXP_DATE)
VALUES
  (-1, -1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO SB_DWH.DIM_CLOS_PRODUCT
  (DIMENSION_KEY, PRODUCT_SK, PRODUCT_BK, PRODUCT_LINE_CODE, PRODUCT_LINE_NAME, SUB_PRODUCT_CODE, SUB_PRODUCT_NAME, EFF_DATE, EXP_DATE)
VALUES
  (-1, -1, NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO SB_DWH.DIM_CLOS_WORKSTEP_DECISION
  (DIMENSION_KEY, WORKSTEP_DECISION_SK, WORKSTEP_DECISION_BK, WORKSTEP_CODE, DECISION_CODE, CHANNEL, EFF_DATE, EXP_DATE)
VALUES
  (-1, -1, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO SB_DWH.DIM_LOS_COMPANY
  (DIMENSION_KEY, COMPANY_SK, COMPANY_CODE, COMPANY_NAME, COMPANY_ADDRESS, COMPANY_EMAIL, ZONE, BRANCH_CODE, BRANCH_NAME, CITY, DISTRICT, REGION_CODE, REGION_NAME, EFF_DATE, EXP_DATE)
VALUES
  (-1, -1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO SB_DWH.DIM_LOS_USER
  (DIMENSION_KEY, USER_SK, USERNAME, EMPLOYEE_NAME, EMPLOYEE_STATUS, EMAIL, IP_PHONE, SB_CODE, ID_CUSTOMER, COMPANY_CODE, COMPANY_NAME, TITLE, DEPARTMENT_CODE, DEPARTMENT_NAME, UWMAKER_GROUP, UWCHECKER_GROUP, AP_GROUP, PREDISB_MAKER_GROUP, PREDISB_GROUP, DISB_MAKER_GROUP, DISB_CHECKER_GROUP, HUB, BRANCH_MANAGER_EMAIL, EFF_DATE, EXP_DATE)
VALUES
  (-1, -1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO SB_DWH.DIM_RLOS_APPLICATION
  (DIMENSION_KEY, APPLICATION_SK, WI_NAME, LOANCASEID, STREAM, POLICY, CAMPAIGN, PROOF_OF_INCOME, COLL_REQUIRE, IS_SEC_PRODUCT, DEVIATION_FLAG, CREATE_EMPLOYEE_CODE, CREATE_EMPLOYEE_NAME, CREATION_DATE, APPLICATION_DATE, RESULT_MAIN_CARD_ID, APP_GRP, LAST_APPROVAL_DATE, CUSTOMER_NAME, APPROVAL_CONDITION, APPROVER_TYPE, APP_STATUS, RMEMAILID, REMARKS, ZONE, SALE_TYPE, BROKER_TYPE, BROKER_ID, BROKER_NAME, ACC_OFFICER, ACCOUNT_OFFICER_NAME, EXISTING_CUSTOMER, APPLICANT_CIF, KYC1, INTEREST_RATE_PCT, LOAN_TO_VALUE, LOAN_OBJECTIVE, TOTAL_INCOME, SALARYFLAG, CARFLAG, HOUSEFLAG, ENTERPRISSEFLAG, DIVINGFLAG, FAIMILYFLAG, NONLICFLAG, WAGESFLAG, PENSIONFLAG, OTHERFLAG, PRODUCT_NAME, C_PHONE_CREATE_FLAG, C_PHONE_DELETE_FLAG, C_FI_CREATE_FLAG, C_FI_DELETE_FLAG, C_LEGAL_CREATE_FLAG, C_LEGAL_DELETE_FLAG, REINITIATE, NORMALBRHOLD, REGBRHOLD, STP_FLAG, ELIGIBLE, TOTALNONELIGIBLE, CANCEL_REASON, EFF_DATE, EXP_DATE)
VALUES
  (-1, -1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO SB_DWH.DIM_RLOS_CARD_PROMOTION
  (DIMENSION_KEY, CARD_PROMOTION_SK, PROMOTION_CODE, PROMOTION_DESC, EFF_DATE, EXP_DATE)
VALUES
  (-1, -1, NULL, NULL, NULL, NULL);

INSERT INTO SB_DWH.DIM_RLOS_CHANGE_TYPE
  (DIMENSION_KEY, CHANGE_TYPE_SK, CHANGE_TYPE_BK, CHANGE_TYPE_CODE, CHANGE_TYPE_NAME, DETAIL_CHANGE_TYPE_CODE, DETAIL_CHANGE_TYPE_NAME, EFF_DATE, EXP_DATE)
VALUES
  (-1, -1, NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO SB_DWH.DIM_RLOS_EXCEPTION
  (DIMENSION_KEY, EXCEPTION_SK, EXCEPTION_BK, ACTIVITYNAME, DECISION_CODE, EXCEPTION_CATEGORY, EXCEPTION_NAME, EXCEPTION_CODE, RAISE_FLAG, CLEAR_FLAG, ID_SOURCE, CODE_SOURCE, STATUS, EFF_DATE, EXP_DATE)
VALUES
  (-1, -1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO SB_DWH.DIM_RLOS_PRODUCT
  (DIMENSION_KEY, PRODUCT_SK, PRODUCT_BK, PRODUCTLINE_CODE, PRODUCTLINE_NAME, SUB_PRODUCT_CODE, SUB_PRODUCT_NAME, SCORE_REQUIRED, SCORE_MODEL, EFF_DATE, EXP_DATE)
VALUES
  (-1, -1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO SB_DWH.DIM_RLOS_SECONDPRODUCT
  (DIMENSION_KEY, SECONDPRODUCT_SK, SECONDPRODUCT_BK, PRODUCTLINE_CODE, PRODUCTLINE_NAME, SECONDARY_PRODUCT, EFF_DATE, EXP_DATE)
VALUES
  (-1, -1, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO SB_DWH.DIM_RLOS_WORKSTEP_DECISION
  (DIMENSION_KEY, WORKSTEP_DECISION_SK, WORKSTEP_DECISION_BK, WORKSTEP_CODE, DECISION_CODE, EFF_DATE, EXP_DATE)
VALUES
  (-1, -1, NULL, NULL, NULL, NULL, NULL);

COMMIT;
