-- ============================================================
-- PDTD_DTM_DROP_ALL.sql
-- Drop tat ca cac bang vung PDTD_DTM (thu tu: AGG + FACT -> DIM)
-- ============================================================

-- AGG + FACT (19 bang)
DROP TABLE PDTD_DTM.AGG_LOS_KPI_APPLICATION PURGE;
DROP TABLE PDTD_DTM.AGG_LOS_KPI_USER_YEAR PURGE;
DROP TABLE PDTD_DTM.AGG_LOS_KPI_YTD_DAILY PURGE;
DROP TABLE PDTD_DTM.FCT_CLOS_APPLICATION PURGE;
DROP TABLE PDTD_DTM.FCT_CLOS_COLLATERAL PURGE;
DROP TABLE PDTD_DTM.FCT_CLOS_DEVIATION PURGE;
DROP TABLE PDTD_DTM.FCT_CLOS_EXCEPTION PURGE;
DROP TABLE PDTD_DTM.FCT_CLOS_LEGAL_PARTY PURGE;
DROP TABLE PDTD_DTM.FCT_CLOS_LOAN_DISBURSEMENT PURGE;
DROP TABLE PDTD_DTM.FCT_CLOS_WORKSTEP_EVENT PURGE;
DROP TABLE PDTD_DTM.FCT_RLOS_APPLICATION_SECONDPRODUCT PURGE;
DROP TABLE PDTD_DTM.FCT_RLOS_APPLICATION PURGE;
DROP TABLE PDTD_DTM.FCT_RLOS_COLLATERAL PURGE;
DROP TABLE PDTD_DTM.FCT_RLOS_COREPAYER PURGE;
DROP TABLE PDTD_DTM.FCT_RLOS_CUSTOMER PURGE;
DROP TABLE PDTD_DTM.FCT_RLOS_DEVIATION PURGE;
DROP TABLE PDTD_DTM.FCT_RLOS_EXCEPTION PURGE;
DROP TABLE PDTD_DTM.FCT_RLOS_LOAN_DISBURSEMENT PURGE;
DROP TABLE PDTD_DTM.FCT_RLOS_WORKSTEP_EVENT PURGE;

-- DIM (14 bang)
DROP TABLE PDTD_DTM.DIM_CLOS_APPLICATION PURGE;
DROP TABLE PDTD_DTM.DIM_CLOS_CUSTOMER PURGE;
DROP TABLE PDTD_DTM.DIM_CLOS_EXCEPTION PURGE;
DROP TABLE PDTD_DTM.DIM_CLOS_PRODUCT PURGE;
DROP TABLE PDTD_DTM.DIM_CLOS_WORKSTEP_DECISION PURGE;
DROP TABLE PDTD_DTM.DIM_LOS_COMPANY PURGE;
DROP TABLE PDTD_DTM.DIM_LOS_USER PURGE;
DROP TABLE PDTD_DTM.DIM_RLOS_APPLICATION PURGE;
DROP TABLE PDTD_DTM.DIM_RLOS_CARD_PROMOTION PURGE;
DROP TABLE PDTD_DTM.DIM_RLOS_CHANGE_TYPE PURGE;
DROP TABLE PDTD_DTM.DIM_RLOS_EXCEPTION PURGE;
DROP TABLE PDTD_DTM.DIM_RLOS_PRODUCT PURGE;
DROP TABLE PDTD_DTM.DIM_RLOS_SECONDPRODUCT PURGE;
DROP TABLE PDTD_DTM.DIM_RLOS_WORKSTEP_DECISION PURGE;

COMMIT;
