-- ============================================================
-- SB_DWH_DROP_ALL.sql
-- Drop tat ca cac bang vung SB_DWH (thu tu: FACT -> DIM -> WRK)
-- ============================================================

-- FACT (14 bang)
DROP TABLE SB_DWH.FCT_CLOS_APPLICATION PURGE;
DROP TABLE SB_DWH.FCT_CLOS_COLLATERAL PURGE;
DROP TABLE SB_DWH.FCT_CLOS_DEVIATION PURGE;
DROP TABLE SB_DWH.FCT_CLOS_EXCEPTION PURGE;
DROP TABLE SB_DWH.FCT_CLOS_LEGAL_PARTY PURGE;
DROP TABLE SB_DWH.FCT_CLOS_WORKSTEP_EVENT PURGE;
DROP TABLE SB_DWH.FCT_RLOS_APPLICATION_SECONDPRODUCT PURGE;
DROP TABLE SB_DWH.FCT_RLOS_APPLICATION PURGE;
DROP TABLE SB_DWH.FCT_RLOS_COLLATERAL PURGE;
DROP TABLE SB_DWH.FCT_RLOS_COREPAYER PURGE;
DROP TABLE SB_DWH.FCT_RLOS_CUSTOMER PURGE;
DROP TABLE SB_DWH.FCT_RLOS_DEVIATION PURGE;
DROP TABLE SB_DWH.FCT_RLOS_EXCEPTION PURGE;
DROP TABLE SB_DWH.FCT_RLOS_WORKSTEP_EVENT PURGE;

-- DIM (14 bang)
DROP TABLE SB_DWH.DIM_CLOS_APPLICATION PURGE;
DROP TABLE SB_DWH.DIM_CLOS_CUSTOMER PURGE;
DROP TABLE SB_DWH.DIM_CLOS_EXCEPTION PURGE;
DROP TABLE SB_DWH.DIM_CLOS_PRODUCT PURGE;
DROP TABLE SB_DWH.DIM_CLOS_WORKSTEP_DECISION PURGE;
DROP TABLE SB_DWH.DIM_LOS_COMPANY PURGE;
DROP TABLE SB_DWH.DIM_LOS_USER PURGE;
DROP TABLE SB_DWH.DIM_RLOS_APPLICATION PURGE;
DROP TABLE SB_DWH.DIM_RLOS_CARD_PROMOTION PURGE;
DROP TABLE SB_DWH.DIM_RLOS_CHANGE_TYPE PURGE;
DROP TABLE SB_DWH.DIM_RLOS_EXCEPTION PURGE;
DROP TABLE SB_DWH.DIM_RLOS_PRODUCT PURGE;
DROP TABLE SB_DWH.DIM_RLOS_SECONDPRODUCT PURGE;
DROP TABLE SB_DWH.DIM_RLOS_WORKSTEP_DECISION PURGE;

-- WRK (14 bang)
DROP TABLE SB_DWH.WRK_DIM_CLOS_APPLICATION PURGE;
DROP TABLE SB_DWH.WRK_DIM_CLOS_CUSTOMER PURGE;
DROP TABLE SB_DWH.WRK_DIM_CLOS_EXCEPTION PURGE;
DROP TABLE SB_DWH.WRK_DIM_CLOS_PRODUCT PURGE;
DROP TABLE SB_DWH.WRK_DIM_CLOS_WORKSTEP_DECISION PURGE;
DROP TABLE SB_DWH.WRK_DIM_LOS_COMPANY PURGE;
DROP TABLE SB_DWH.WRK_DIM_LOS_USER PURGE;
DROP TABLE SB_DWH.WRK_DIM_RLOS_APPLICATION PURGE;
DROP TABLE SB_DWH.WRK_DIM_RLOS_CARD_PROMOTION PURGE;
DROP TABLE SB_DWH.WRK_DIM_RLOS_CHANGE_TYPE PURGE;
DROP TABLE SB_DWH.WRK_DIM_RLOS_EXCEPTION PURGE;
DROP TABLE SB_DWH.WRK_DIM_RLOS_PRODUCT PURGE;
DROP TABLE SB_DWH.WRK_DIM_RLOS_SECONDPRODUCT PURGE;
DROP TABLE SB_DWH.WRK_DIM_RLOS_WORKSTEP_DECISION PURGE;

COMMIT;
