-- SB_DWH: tao 14 sequence sinh DIMENSION_KEY cho cac bang DIM.
-- Chay 1 lan. Neu sequence da ton tai, script se bao loi va dung lai.
-- PDTD_DTM giu nguyen DIMENSION_KEY tu SB_DWH, KHONG tao sequence moi.

-- DIM_CLOS_APPLICATION.DIMENSION_KEY
CREATE SEQUENCE SB_DWH.SEQ_DIM_CLOS_APPLICATION START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCYCLE CACHE 20;

-- DIM_CLOS_CUSTOMER.DIMENSION_KEY
CREATE SEQUENCE SB_DWH.SEQ_DIM_CLOS_CUSTOMER START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCYCLE CACHE 20;

-- DIM_CLOS_EXCEPTION.DIMENSION_KEY
CREATE SEQUENCE SB_DWH.SEQ_DIM_CLOS_EXCEPTION START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCYCLE CACHE 20;

-- DIM_CLOS_PRODUCT.DIMENSION_KEY
CREATE SEQUENCE SB_DWH.SEQ_DIM_CLOS_PRODUCT START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCYCLE CACHE 20;

-- DIM_CLOS_WORKSTEP_DECISION.DIMENSION_KEY
CREATE SEQUENCE SB_DWH.SEQ_DIM_CLOS_WORKSTEP_DECISION START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCYCLE CACHE 20;

-- DIM_LOS_COMPANY.DIMENSION_KEY
CREATE SEQUENCE SB_DWH.SEQ_DIM_LOS_COMPANY START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCYCLE CACHE 20;

-- DIM_LOS_USER.DIMENSION_KEY
CREATE SEQUENCE SB_DWH.SEQ_DIM_LOS_USER START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCYCLE CACHE 20;

-- DIM_RLOS_APPLICATION.DIMENSION_KEY
CREATE SEQUENCE SB_DWH.SEQ_DIM_RLOS_APPLICATION START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCYCLE CACHE 20;

-- DIM_RLOS_CARD_PROMOTION.DIMENSION_KEY
CREATE SEQUENCE SB_DWH.SEQ_DIM_RLOS_CARD_PROMOTION START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCYCLE CACHE 20;

-- DIM_RLOS_CHANGE_TYPE.DIMENSION_KEY
CREATE SEQUENCE SB_DWH.SEQ_DIM_RLOS_CHANGE_TYPE START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCYCLE CACHE 20;

-- DIM_RLOS_EXCEPTION.DIMENSION_KEY
CREATE SEQUENCE SB_DWH.SEQ_DIM_RLOS_EXCEPTION START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCYCLE CACHE 20;

-- DIM_RLOS_PRODUCT.DIMENSION_KEY
CREATE SEQUENCE SB_DWH.SEQ_DIM_RLOS_PRODUCT START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCYCLE CACHE 20;

-- DIM_RLOS_SECONDPRODUCT.DIMENSION_KEY
CREATE SEQUENCE SB_DWH.SEQ_DIM_RLOS_SECONDPRODUCT START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCYCLE CACHE 20;

-- DIM_RLOS_WORKSTEP_DECISION.DIMENSION_KEY
CREATE SEQUENCE SB_DWH.SEQ_DIM_RLOS_WORKSTEP_DECISION START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCYCLE CACHE 20;
