-- SB_DWH: tao 14 sequence sinh DIMENSION_KEY cho cac bang DIM.
-- Chay 1 lan trong SQL Window (F8). DROP SEQUENCE neu da co roi tao lai => khoa bat dau lai tu 1.
-- PDTD_DTM giu nguyen DIMENSION_KEY tu SB_DWH, KHONG tao sequence moi.
BEGIN
   -- DIM_CLOS_APPLICATION.DIMENSION_KEY
   BEGIN
      EXECUTE IMMEDIATE 'DROP SEQUENCE SB_DWH.SEQ_DIM_CLOS_APPLICATION';
   EXCEPTION
      WHEN OTHERS THEN IF SQLCODE != -2289 THEN RAISE; END IF;
   END;
   BEGIN
      EXECUTE IMMEDIATE 'CREATE SEQUENCE SB_DWH.SEQ_DIM_CLOS_APPLICATION START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCYCLE CACHE 20';
   EXCEPTION
      WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
   END;
   -- DIM_CLOS_CUSTOMER.DIMENSION_KEY
   BEGIN
      EXECUTE IMMEDIATE 'DROP SEQUENCE SB_DWH.SEQ_DIM_CLOS_CUSTOMER';
   EXCEPTION
      WHEN OTHERS THEN IF SQLCODE != -2289 THEN RAISE; END IF;
   END;
   BEGIN
      EXECUTE IMMEDIATE 'CREATE SEQUENCE SB_DWH.SEQ_DIM_CLOS_CUSTOMER START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCYCLE CACHE 20';
   EXCEPTION
      WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
   END;
   -- DIM_CLOS_EXCEPTION.DIMENSION_KEY
   BEGIN
      EXECUTE IMMEDIATE 'DROP SEQUENCE SB_DWH.SEQ_DIM_CLOS_EXCEPTION';
   EXCEPTION
      WHEN OTHERS THEN IF SQLCODE != -2289 THEN RAISE; END IF;
   END;
   BEGIN
      EXECUTE IMMEDIATE 'CREATE SEQUENCE SB_DWH.SEQ_DIM_CLOS_EXCEPTION START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCYCLE CACHE 20';
   EXCEPTION
      WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
   END;
   -- DIM_CLOS_PRODUCT.DIMENSION_KEY
   BEGIN
      EXECUTE IMMEDIATE 'DROP SEQUENCE SB_DWH.SEQ_DIM_CLOS_PRODUCT';
   EXCEPTION
      WHEN OTHERS THEN IF SQLCODE != -2289 THEN RAISE; END IF;
   END;
   BEGIN
      EXECUTE IMMEDIATE 'CREATE SEQUENCE SB_DWH.SEQ_DIM_CLOS_PRODUCT START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCYCLE CACHE 20';
   EXCEPTION
      WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
   END;
   -- DIM_CLOS_WORKSTEP_DECISION.DIMENSION_KEY
   BEGIN
      EXECUTE IMMEDIATE 'DROP SEQUENCE SB_DWH.SEQ_DIM_CLOS_WORKSTEP_DECISION';
   EXCEPTION
      WHEN OTHERS THEN IF SQLCODE != -2289 THEN RAISE; END IF;
   END;
   BEGIN
      EXECUTE IMMEDIATE 'CREATE SEQUENCE SB_DWH.SEQ_DIM_CLOS_WORKSTEP_DECISION START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCYCLE CACHE 20';
   EXCEPTION
      WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
   END;
   -- DIM_LOS_COMPANY.DIMENSION_KEY
   BEGIN
      EXECUTE IMMEDIATE 'DROP SEQUENCE SB_DWH.SEQ_DIM_LOS_COMPANY';
   EXCEPTION
      WHEN OTHERS THEN IF SQLCODE != -2289 THEN RAISE; END IF;
   END;
   BEGIN
      EXECUTE IMMEDIATE 'CREATE SEQUENCE SB_DWH.SEQ_DIM_LOS_COMPANY START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCYCLE CACHE 20';
   EXCEPTION
      WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
   END;
   -- DIM_LOS_USER.DIMENSION_KEY
   BEGIN
      EXECUTE IMMEDIATE 'DROP SEQUENCE SB_DWH.SEQ_DIM_LOS_USER';
   EXCEPTION
      WHEN OTHERS THEN IF SQLCODE != -2289 THEN RAISE; END IF;
   END;
   BEGIN
      EXECUTE IMMEDIATE 'CREATE SEQUENCE SB_DWH.SEQ_DIM_LOS_USER START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCYCLE CACHE 20';
   EXCEPTION
      WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
   END;
   -- DIM_RLOS_APPLICATION.DIMENSION_KEY
   BEGIN
      EXECUTE IMMEDIATE 'DROP SEQUENCE SB_DWH.SEQ_DIM_RLOS_APPLICATION';
   EXCEPTION
      WHEN OTHERS THEN IF SQLCODE != -2289 THEN RAISE; END IF;
   END;
   BEGIN
      EXECUTE IMMEDIATE 'CREATE SEQUENCE SB_DWH.SEQ_DIM_RLOS_APPLICATION START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCYCLE CACHE 20';
   EXCEPTION
      WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
   END;
   -- DIM_RLOS_CARD_PROMOTION.DIMENSION_KEY
   BEGIN
      EXECUTE IMMEDIATE 'DROP SEQUENCE SB_DWH.SEQ_DIM_RLOS_CARD_PROMOTION';
   EXCEPTION
      WHEN OTHERS THEN IF SQLCODE != -2289 THEN RAISE; END IF;
   END;
   BEGIN
      EXECUTE IMMEDIATE 'CREATE SEQUENCE SB_DWH.SEQ_DIM_RLOS_CARD_PROMOTION START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCYCLE CACHE 20';
   EXCEPTION
      WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
   END;
   -- DIM_RLOS_CHANGE_TYPE.DIMENSION_KEY
   BEGIN
      EXECUTE IMMEDIATE 'DROP SEQUENCE SB_DWH.SEQ_DIM_RLOS_CHANGE_TYPE';
   EXCEPTION
      WHEN OTHERS THEN IF SQLCODE != -2289 THEN RAISE; END IF;
   END;
   BEGIN
      EXECUTE IMMEDIATE 'CREATE SEQUENCE SB_DWH.SEQ_DIM_RLOS_CHANGE_TYPE START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCYCLE CACHE 20';
   EXCEPTION
      WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
   END;
   -- DIM_RLOS_EXCEPTION.DIMENSION_KEY
   BEGIN
      EXECUTE IMMEDIATE 'DROP SEQUENCE SB_DWH.SEQ_DIM_RLOS_EXCEPTION';
   EXCEPTION
      WHEN OTHERS THEN IF SQLCODE != -2289 THEN RAISE; END IF;
   END;
   BEGIN
      EXECUTE IMMEDIATE 'CREATE SEQUENCE SB_DWH.SEQ_DIM_RLOS_EXCEPTION START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCYCLE CACHE 20';
   EXCEPTION
      WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
   END;
   -- DIM_RLOS_PRODUCT.DIMENSION_KEY
   BEGIN
      EXECUTE IMMEDIATE 'DROP SEQUENCE SB_DWH.SEQ_DIM_RLOS_PRODUCT';
   EXCEPTION
      WHEN OTHERS THEN IF SQLCODE != -2289 THEN RAISE; END IF;
   END;
   BEGIN
      EXECUTE IMMEDIATE 'CREATE SEQUENCE SB_DWH.SEQ_DIM_RLOS_PRODUCT START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCYCLE CACHE 20';
   EXCEPTION
      WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
   END;
   -- DIM_RLOS_SECONDPRODUCT.DIMENSION_KEY
   BEGIN
      EXECUTE IMMEDIATE 'DROP SEQUENCE SB_DWH.SEQ_DIM_RLOS_SECONDPRODUCT';
   EXCEPTION
      WHEN OTHERS THEN IF SQLCODE != -2289 THEN RAISE; END IF;
   END;
   BEGIN
      EXECUTE IMMEDIATE 'CREATE SEQUENCE SB_DWH.SEQ_DIM_RLOS_SECONDPRODUCT START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCYCLE CACHE 20';
   EXCEPTION
      WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
   END;
   -- DIM_RLOS_WORKSTEP_DECISION.DIMENSION_KEY
   BEGIN
      EXECUTE IMMEDIATE 'DROP SEQUENCE SB_DWH.SEQ_DIM_RLOS_WORKSTEP_DECISION';
   EXCEPTION
      WHEN OTHERS THEN IF SQLCODE != -2289 THEN RAISE; END IF;
   END;
   BEGIN
      EXECUTE IMMEDIATE 'CREATE SEQUENCE SB_DWH.SEQ_DIM_RLOS_WORKSTEP_DECISION START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCYCLE CACHE 20';
   EXCEPTION
      WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
   END;
END;
