-- ============================================================
-- SB_DWH_FACT_DROP_ALL.sql
-- Drop tat ca cac bang duoc tao trong SB_DWH_FACT_ALL.sql
-- ============================================================
DROP TABLE SB_DWH.FCT_CLOS_APPLICATION PURGE;
DROP TABLE SB_DWH.FCT_CLOS_COLLATERAL PURGE;
DROP TABLE SB_DWH.FCT_CLOS_DEVIATION PURGE;
DROP TABLE SB_DWH.FCT_CLOS_EXCEPTION PURGE;
DROP TABLE SB_DWH.FCT_CLOS_LEGAL_PARTY PURGE;
DROP TABLE SB_DWH.FCT_CLOS_WORKSTEP_EVENT PURGE;
DROP TABLE SB_DWH.FCT_RLOS_APPLICATION_SECONDPRODUCT PURGE;
DROP TABLE SB_DWH.FCT_RLOS_APPLICATION PURGE;
DROP TABLE SB_DWH.FCT_RLOS_COLLATERAL PURGE;
DROP TABLE SB_DWH.FCT_RLOS_COREPAYER PURGE;
DROP TABLE SB_DWH.FCT_RLOS_CUSTOMER PURGE;
DROP TABLE SB_DWH.FCT_RLOS_DEVIATION PURGE;
DROP TABLE SB_DWH.FCT_RLOS_EXCEPTION PURGE;
DROP TABLE SB_DWH.FCT_RLOS_WORKSTEP_EVENT PURGE;

COMMIT;
