/* ======================================================================
   SB_DWH - Sequence sinh DIMENSION_KEY cho cac bang DIM
   - Moi DIM SB_DWH co 1 sequence rieng: SB_DWH.SEQ_<TEN_BANG>
   - PDTD_DTM giu nguyen DIMENSION_KEY tu SB_DWH, KHONG tao sequence moi
   - Bat dau tu 1 (gia tri -1 danh cho dong Unknown)
   - Chay lai an toan: sequence da ton tai (ORA-00955) thi bo qua,
     khong DROP nen khong reset gia tri khoa dang dung
   ====================================================================== */

-- DIM_CLOS_APPLICATION.DIMENSION_KEY
BEGIN
  EXECUTE IMMEDIATE 'CREATE SEQUENCE SB_DWH.SEQ_DIM_CLOS_APPLICATION
    START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCYCLE CACHE 20';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- DIM_CLOS_CUSTOMER.DIMENSION_KEY
BEGIN
  EXECUTE IMMEDIATE 'CREATE SEQUENCE SB_DWH.SEQ_DIM_CLOS_CUSTOMER
    START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCYCLE CACHE 20';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- DIM_CLOS_EXCEPTION.DIMENSION_KEY
BEGIN
  EXECUTE IMMEDIATE 'CREATE SEQUENCE SB_DWH.SEQ_DIM_CLOS_EXCEPTION
    START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCYCLE CACHE 20';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- DIM_CLOS_PRODUCT.DIMENSION_KEY
BEGIN
  EXECUTE IMMEDIATE 'CREATE SEQUENCE SB_DWH.SEQ_DIM_CLOS_PRODUCT
    START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCYCLE CACHE 20';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- DIM_CLOS_WORKSTEP_DECISION.DIMENSION_KEY
BEGIN
  EXECUTE IMMEDIATE 'CREATE SEQUENCE SB_DWH.SEQ_DIM_CLOS_WORKSTEP_DECISION
    START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCYCLE CACHE 20';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- DIM_LOS_COMPANY.DIMENSION_KEY
BEGIN
  EXECUTE IMMEDIATE 'CREATE SEQUENCE SB_DWH.SEQ_DIM_LOS_COMPANY
    START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCYCLE CACHE 20';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- DIM_LOS_USER.DIMENSION_KEY
BEGIN
  EXECUTE IMMEDIATE 'CREATE SEQUENCE SB_DWH.SEQ_DIM_LOS_USER
    START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCYCLE CACHE 20';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- DIM_RLOS_APPLICATION.DIMENSION_KEY
BEGIN
  EXECUTE IMMEDIATE 'CREATE SEQUENCE SB_DWH.SEQ_DIM_RLOS_APPLICATION
    START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCYCLE CACHE 20';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- DIM_RLOS_CARD_PROMOTION.DIMENSION_KEY
BEGIN
  EXECUTE IMMEDIATE 'CREATE SEQUENCE SB_DWH.SEQ_DIM_RLOS_CARD_PROMOTION
    START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCYCLE CACHE 20';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- DIM_RLOS_CHANGE_TYPE.DIMENSION_KEY
BEGIN
  EXECUTE IMMEDIATE 'CREATE SEQUENCE SB_DWH.SEQ_DIM_RLOS_CHANGE_TYPE
    START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCYCLE CACHE 20';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- DIM_RLOS_EXCEPTION.DIMENSION_KEY
BEGIN
  EXECUTE IMMEDIATE 'CREATE SEQUENCE SB_DWH.SEQ_DIM_RLOS_EXCEPTION
    START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCYCLE CACHE 20';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- DIM_RLOS_PRODUCT.DIMENSION_KEY
BEGIN
  EXECUTE IMMEDIATE 'CREATE SEQUENCE SB_DWH.SEQ_DIM_RLOS_PRODUCT
    START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCYCLE CACHE 20';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- DIM_RLOS_SECONDPRODUCT.DIMENSION_KEY
BEGIN
  EXECUTE IMMEDIATE 'CREATE SEQUENCE SB_DWH.SEQ_DIM_RLOS_SECONDPRODUCT
    START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCYCLE CACHE 20';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- DIM_RLOS_WORKSTEP_DECISION.DIMENSION_KEY
BEGIN
  EXECUTE IMMEDIATE 'CREATE SEQUENCE SB_DWH.SEQ_DIM_RLOS_WORKSTEP_DECISION
    START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCYCLE CACHE 20';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- Kiem tra
SELECT sequence_name, last_number
  FROM all_sequences
 WHERE sequence_owner = 'SB_DWH'
   AND sequence_name LIKE 'SEQ_DIM%'
 ORDER BY sequence_name;
